#!/usr/bin/env python2

import serial
import sys
import time

while(True):
	try:
		ser = serial.Serial('/dev/ttyUSB0', 57600, timeout=1)
		while(True):
			while(ser.inWaiting()):
				sys.stdout.write(ser.read())
				sys.stdout.flush()
			time.sleep(0.05)
	except serial.SerialException:
		pass
	finally:
		pass

