#!/usr/bin/env python

import serial
import sys
import time


ser = serial.Serial('/dev/ttyUSB0', 57600, timeout=1)
run = True
while(run):
	while(ser.inWaiting()):
		sys.stdout.write(ser.read())
		sys.stdout.flush()
	time.sleep(0.05)

ser.close()


