#!/usr/bin/env python

import serial
import sys


ser = serial.Serial('/dev/ttyUSB0', 57600, timeout=1)
run = True
while(run):
	while(ser.inWaiting()):
		sys.stdout.write(ser.read())
		sys.stdout.flush()

ser.close()


